#production_url是sitemap.txt生成的url,方便百度谷歌收录
production_url: http://www.ivaneye.com
#
# Jekyll Settings
#
markdown: redcarpet   # [ maruku | rdiscount | kramdown | redcarpet ]
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
markdown_ext:  markdown,mkd,mkdn,md
highlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page/:num"
exclude: [ "README.md",".idea",".iml",".name",".Node"]
encoding: "utf-8"
#在发布文章时使用一个未来的日期
future: true
#产生相关页面的索引
lsi:      false
#禁用定制插件
safe:     false

#CDN_PATH:   http://7xipn4.com1.z0.glb.clouddn.com
